# Site wide configuration

title: Patrice Bechard
description: B.Sc. Physics at Université de Montréal
logo: twitter_card.jpg # 120x120 px default image used for Twitter summary card
teaser: cover_photo.jpg # 400x250 px default teaser image used in image archive grid
locale: en
url: patricebechard.github.io

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner: Patrice Bechard
  name: Patrice Bechard
  email: bechardpatrice@gmail.com
  twitter: patricebechard
  google:
    ad-client:
    ad-slot:
  bio: I am completing my B.Sc. in physics at Université de Montréal. I am presently doing an internship in astrophysics under the supervision of Pierre Bergeron.
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
